spring.application.name=DiscoveryServer
server.port=8761

#Nombre del host
eureka.instance.hostname=localhost
#Ruta
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Evitamos que se autoregistre
eureka.client.register-with-eureka=false
#Indicamos que no obtiene el registro de los servicios
eureka.client.fetch-registry=false
#habilitamos la autopreservacion
eureka.server.enable-self-preservation=true
#Exponemos los endpoint para monitoreo
management.endpoints.web.exposure.include=*