spring.application.name=ApiGateway
server.port=8090

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Gateway
spring.cloud.gateway.discovery.locator.enable=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false

#Configuracion de rutas
spring.cloud.gateway.server.webmvc.routes[0].id=Proveedores
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://Proveedores
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/proveedores/**

spring.cloud.gateway.server.webmvc.routes[1].id=Productos
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://Productos
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/productos/**

spring.cloud.gateway.server.webmvc.routes[2].id=Pedidos
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://Pedidos
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/pedidos/**

#Configuracion de Swagger
spring.mvc.format.date=d/M/yyyy
springdoc.swagger-ui.path=/swagger-ui.html

#Base de datos
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=ENUCOM13
spring.datasource.password=enucom
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format-sql=true