CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER,
    NOMBRE NVARCHAR2(100),
    PRECIO NUMBER(8,2),
    STOCK NUMBER,
    CONSTRAINT PK_INVENTARIO
    PRIMARY KEY (ID_INVENTARIO)
);

CREATE UNIQUE INDEX UK_INVENTARIO
ON INVENTARIO (UPPER(NOMBRE));