CREATE OR REPLACE PACKAGE PA_INVENTARIO AS
    PROCEDURE SP_SETINVENTARIO(
        PA_NOMBRE IN VARCHAR,
        PA_PRECIO IN VARCHAR,
        PA_STOCK  IN VARCHAR
    );

    PROCEDURE SP_GETINVENTARIO(
        REC_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_GET_ID_INVENTARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_ID         IN VARCHAR
    );

    PROCEDURE SP_UPDATE_INVENTARIO(        
        PA_NOMBRE IN VARCHAR,
        PA_PRECIO IN VARCHAR,
        PA_STOCK  IN VARCHAR
    );

    PROCEDURE SP_DELETE_INVENTARIO(
        PA_ID  IN VARCHAR
    );

    PROCEDURE SP_TICKET_INVENTARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_PRODUCTO IN VARCHAR,
        PA_CANTIDAD IN VARCHAR
    );
END PA_INVENTARIO;