CREATE OR REPLACE PACKAGE BODY PA_INVENTARIO AS
    PROCEDURE SP_SETINVENTARIO(
        PA_NOMBRE IN VARCHAR,
        PA_PRECIO IN VARCHAR,
        PA_STOCK  IN VARCHAR
    )AS
        v_precio NUMBER;
        v_stock NUMBER;
    BEGIN
        IF TRIM(PA_NOMBRE) IS NULL OR TRIM(PA_PRECIO) IS NULL OR 
        TRIM(PA_STOCK) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN ESPACIOS VACÍOS');
        ELSIF NOT (REGEXP_LIKE(PA_PRECIO ,'^[0-9]+(\.[0-9]+)?$') AND REGEXP_LIKE (PA_STOCK, '^[0-9]+$')) THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL PRECIO O STOCK TIENE QUE SER NUMERICOS');
        ELSE 
            v_precio := TO_NUMBER(TRIM(PA_PRECIO));
            v_stock := TO_NUMBER(TRIM(PA_STOCK));

            INSERT INTO INVENTARIO(NOMBRE, PRECIO, STOCK)
            VALUES (TRIM(PA_NOMBRE), v_precio, v_stock);
        END IF;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL NOMBRE YA EXISTE');

        WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20004, 'ERROR EN CONVERSIÓN DE DATOS');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20099, 'ERROR GENERAL: ' || SQLERRM);

    END SP_SETINVENTARIO;

    PROCEDURE SP_GETINVENTARIO(
        REC_CURSOR OUT SYS_REFCURSOR
    )AS
    BEGIN
        OPEN REC_CURSOR FOR
            SELECT * FROM INVENTARIO
            ORDER BY ID_INVENTARIO;
    END SP_GETINVENTARIO;

    PROCEDURE SP_GET_ID_INVENTARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_ID         IN VARCHAR
    )AS
        v_id NUMBER;
    BEGIN
        IF TRIM(PA_ID) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN ESPACIOS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_ID, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20001, 'EL ID TIENE QUE SER NUMERICO');
        ELSE
            v_id := TO_NUMBER(TRIM(PA_ID));
            OPEN REC_CURSOR FOR
                SELECT * FROM INVENTARIO WHERE ID_INVENTARIO=v_id
                ORDER BY ID_INVENTARIO;
        END IF;
    END SP_GET_ID_INVENTARIO;

    PROCEDURE SP_UPDATE_INVENTARIO(        
        PA_NOMBRE IN VARCHAR,
        PA_PRECIO IN VARCHAR,
        PA_STOCK  IN VARCHAR
    )AS
        v_precio NUMBER;
        v_stock NUMBER;
        v_id NUMBER;
    BEGIN
        IF TRIM(PA_NOMBRE) IS NULL OR TRIM(PA_PRECIO) IS NULL OR 
        TRIM(PA_STOCK) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN ESPACIOS VACÍOS');
        ELSIF NOT (REGEXP_LIKE(PA_PRECIO ,'^[0-9]+(\.[0-9]+)?$')
        AND REGEXP_LIKE (PA_STOCK, '^[0-9]+$')) THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL PRECIO O STOCK TIENE QUE SER NUMERICOS');
        ELSE 
            v_precio := TO_NUMBER(TRIM(PA_PRECIO));
            v_stock := TO_NUMBER(TRIM(PA_STOCK));            

            SELECT ID_INVENTARIO
            INTO v_id FROM INVENTARIO
            WHERE UPPER(NOMBRE)=UPPER(TRIM(PA_NOMBRE));

            UPDATE INVENTARIO SET PRECIO=v_precio, STOCK=v_stock
            WHERE ID_INVENTARIO=v_id;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL PRODUCTO NO EXISTE');
    END SP_UPDATE_INVENTARIO;

    PROCEDURE SP_DELETE_INVENTARIO(
        PA_ID  IN VARCHAR
    )AS
        v_id NUMBER;
    BEGIN
        IF TRIM(PA_ID) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN ESPACIOS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_ID, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL ID TIENE QUE SER NÚMERICO');
        ELSE
            v_id := TO_NUMBER(TRIM(PA_ID));
            DELETE FROM INVENTARIO WHERE ID_INVENTARIO=v_id;
        END IF;
    END SP_DELETE_INVENTARIO;

    PROCEDURE SP_TICKET_INVENTARIO(
        REC_CURSOR  OUT SYS_REFCURSOR,
        PA_PRODUCTO IN VARCHAR,
        PA_CANTIDAD IN VARCHAR
    )AS
        v_stock NUMBER;
        v_cantidad NUMBER;
        v_resultado NUMBER;
        v_total NUMBER;
        v_precio NUMBER;
    BEGIN
        IF TRIM(PA_PRODUCTO) IS NULL OR TRIM(PA_CANTIDAD) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN ESPACIOS VACÍOS');
        ELSIF NOT REGEXP_LIKE(PA_CANTIDAD, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20002, 'LA CANTIDAD TIENE QUE SER NÚMERICA');
        ELSE
            SELECT STOCK, PRECIO
            INTO v_stock, v_precio
            FROM INVENTARIO
            WHERE UPPER(NOMBRE) = UPPER(PA_PRODUCTO);

            v_cantidad:= TO_NUMBER(PA_CANTIDAD);

            IF v_cantidad > v_stock THEN
                RAISE_APPLICATION_ERROR(-20003, 'NO HAY SUFICIENTE STOCK DISPONIBLE, STOCK ACTUAL: ' || v_stock);
            END IF;
            
            v_resultado:= v_stock - v_cantidad;
            v_total:= v_precio * v_cantidad;
            
            UPDATE INVENTARIO SET STOCK = v_resultado 
            WHERE UPPER(NOMBRE) = UPPER(PA_PRODUCTO);
            
            INSERT INTO VENTAS (PRODUCTO, CANTIDAD, PRECIO_UNITARIO, TOTAL)
            VALUES (PA_PRODUCTO, v_cantidad, v_precio, v_total);
            
            OPEN REC_CURSOR FOR
                SELECT NOMBRE AS PRODUCTO, 
                TO_CHAR(PRECIO, 'FM999,999,990.00') AS PRECIO_UNITARIO,
                v_cantidad AS CANTIDAD,
                TO_CHAR(PRECIO * v_cantidad, 'FM999,999,990.00') AS TOTAL
                FROM INVENTARIO WHERE UPPER(NOMBRE) = UPPER(PA_PRODUCTO);
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'EL PRODUCTO NO EXISTE EN EL INVENTARIO.');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20004, SQLERRM);
    END SP_TICKET_INVENTARIO;
END PA_INVENTARIO;